### PR TITLE
week-3 

### PR DESCRIPTION
**Pull request by tian830426**
Good evening 

My name is Helen Lin in discord appellation.(林冠妤)
I ready to hand in week-3 tesk, thanks for your review !

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/2

have a nice day : )

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Size of radio button should be larger.
2. Separating lines should be 1px height with lighter color.
3. Image slider should extend to full width and keep no margin space with navigator bar in mobile version.

**Comment by tian830426** [comment]
good evening 
please review again ,thanks :) (林冠妤)

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/2

**Review by cwpeng — CHANGES_REQUESTED** [review]
Image slider should extend to full width and keep no margin space with navigator bar in mobile version.
3 114 69 52_3000_attraction_2

**Comment by tian830426** [comment]
Good evening 

please review again ,thanks :) (林冠妤)
thanks for your patience 

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/5

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
