### PR TITLE
week-4

### PR DESCRIPTION
**Pull request by tian830426**
Good evening

My name is Helen Lin in discord appellation.(林冠妤)
I ready to hand in week-4 tesk, thanks for your review !

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/5

have a nice day : )

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Sign in/up dialog show be align in center horizontally.
2. Add right link to home page on your website title.

**Comment by tian830426** [comment]
good morning 
please review again ,thanks. (林冠妤)

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/5

have a nice day :)

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Try to align dialog center horizontally, but near to top.
2. Add semi-transparent backdrop when we open dialog.

**Comment by tian830426** [comment]
good afternoon
please review again ,thanks. (林冠妤)

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/5

have a nice day :)

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your page keep semi-transparent after we sign in successfully.

**Comment by tian830426** [comment]
good afternoon
please review again ,thanks. (林冠妤)

http://3.114.69.52:3000/
http://3.114.69.52:3000/attraction/5

have a nice day :)

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
