### PR TITLE
week-1

### PR DESCRIPTION
**Pull request by tian830426**
http://3.114.69.52:3000/api/attractions/1

彭彭您好，我是冠妤，繳交本週作業，謝謝。

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://3.114.69.52:3000/api/attractions/1 is incorrect.
2. "images" field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a string "['Image URL 1', 'Image URL 2', ...]"
3. Use `LIMIT` in SQL to do pagination than get ALL DATA and do it in your own code.

Solve issues and re-request review.

**Comment by tian830426** [comment]
http://3.114.69.52:3000/api/attractions?page=0
彭彭您好，我是冠妤
有修改上週作業了，再麻煩您檢查，是否需修正的地方，謝謝您。

**Review by cwpeng — COMMENTED** [review]
Your APIs are broken.

**Comment by tian830426** [comment]
http://3.114.69.52:3000/api/attractions?page=0

彭彭您好：我有重新送出，有使用nohup 進行背景執行，再麻煩查看謝謝。

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by tian830426** [comment]
彭彭您好 

我是冠妤，繳交week-2
http://3.114.69.52:3000/

thank you :)  have a nice day!

**Comment by cwpeng** [comment]
You should create new pull request for submitting task.

**Comment by tian830426** [comment]
ok, I see ,thanks for your remind :)

**Pull request merged**
