### PR TITLE
week-2

### PR DESCRIPTION
**Pull request by tian830426**
Good afternoon  
My name is Helen Lin in discord appellation.(林冠妤)
I ready to hand in week-2 mission, thanks for your review !

http://3.114.69.52:3000/

have a nice day : )

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Aspect ratio of any images in your page should keep the same as original ones.
2. Your layout in small devices is obviously broken.

**Comment by tian830426** [comment]
I check it right now!

**Comment by tian830426** [comment]
Good afternoon
I already make it right , review again ,thank you :)

http://3.114.69.52:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
